{"stats": {"errors": 1, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:HelperTest", "name": "test_bytes", "time": 0.00029587745666503906, "type": "error", "errtype": "builtins.AttributeError", "message": "'bytes' object has no attribute 'encode'", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/PirosB3Blockchain/python-primer-jsong-pb-sf-072618/test/index_test.py\", line 9, in test_bytes\n    self.assertEqual(b, str_to_bytes(s))\n  File \"/home/PirosB3Blockchain/python-primer-jsong-pb-sf-072618/index.ipynb\", line 97, in str_to_bytes\n    \"metadata\": {},\nAttributeError: 'bytes' object has no attribute 'encode'\n"}]}